name: Check and Fix Format
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier
        run: |
          prettier --write "./**/*.{js,css,json}"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || (git add . && git commit -m "Apply prettier changes")
          git push
